"""
Provided by your teacher. Do not edit this file.

Write your program in game.py. It must define:

    setup()                 create and return your starting state
    draw(screen, state)     draw the current state on the screen

It may also define any of these. Leave out the ones you do not need.

    app_size                        a pair like (640, 480)
    on_tick(state, dt)              called about 60 times a second;
                                    dt is the seconds since the last call
    on_key_down(state, key)         a key was pressed
    on_key_up(state, key)           a key was released
    on_mouse_down(state, pos, button)
    on_mouse_up(state, pos, button)
    on_mouse_move(state, pos)       pos is an (x, y) pair

If something goes wrong in your code, the error will be shown on screen.
"""

import asyncio
import traceback

import pygame

DEFAULT_APP_SIZE = (640, 480)
FRAMES_PER_SECOND = 60
LONGEST_TICK = 0.1  # seconds; keeps one slow frame from teleporting things
MARGIN = 16

# Load the student's module now, but do not crash if it is broken:
# we want to report the problem on screen rather than show a blank page.
game = None
startup_error = None
try:
    import game
except Exception as exc:
    startup_error = exc


class CallbackError(Exception):
    """Wraps an error raised inside one of game.py's functions."""

    def __init__(self, name, original):
        super().__init__(name)
        self.name = name
        self.original = original


def call(name, *args):
    """Call game.<name>(*args) if it exists, reporting which one failed."""
    handler = getattr(game, name, None)
    if handler is None:
        return
    try:
        handler(*args)
    except Exception as exc:
        raise CallbackError(name, exc) from exc


def get_app_size():
    size = getattr(game, "app_size", DEFAULT_APP_SIZE)
    try:
        width, height = size
        return (int(width), int(height))
    except Exception:
        print(f"app_size should be a pair of numbers like (640, 480); got {size!r}.")
        print(f"Using {DEFAULT_APP_SIZE} instead.")
        return DEFAULT_APP_SIZE


def _tidy(raw):
    """Drop frames from this file and shorten pygbag's unpack paths."""
    kept = []
    i = 0
    while i < len(raw):
        line = raw[i].replace("\t", "    ").rstrip()
        i += 1
        if not line.strip():
            continue
        if '"<console>"' in line:
            # Drop the source line beneath it, if there is one. Under pygbag
            # there usually is not, so check before skipping.
            if i < len(raw) and raw[i].startswith("    ") and 'File "' not in raw[i]:
                i += 1
            continue
        if 'File "' in line:
            before, _, rest = line.partition('File "')
            path, _, after = rest.partition('"')
            line = "  " + path.split("/")[-1] + after
        kept.append(line)
    return kept


def _is_caret_line(line):
    stripped = line.strip()
    return bool(stripped) and set(stripped) <= set("^~")


def _wrap(text, font, width):
    if font.size(text)[0] <= width:
        return [text]
    indent = " " * (len(text) - len(text.lstrip()))
    pieces = []
    current = indent
    for word in text.split():
        trial = current + word if not current.strip() else current + " " + word
        if font.size(trial)[0] <= width or not current.strip():
            current = trial
        else:
            pieces.append(current)
            current = indent + "  " + word
    if current.strip():
        pieces.append(current)
    return pieces


def _render(screen, lines):
    font = pygame.font.Font(None, 26)
    width = screen.get_width() - 2 * MARGIN
    step = font.get_linesize()

    screen.fill((12, 12, 20))
    y = MARGIN
    source = None  # (text, y) of the last source line that fitted on one line

    for line in lines:
        # A caret line is drawn as an underline beneath the token it points at,
        # measured in pixels so it lands in exactly the right place.
        if _is_caret_line(line) and source is not None:
            text, text_y = source
            start = len(line) - len(line.lstrip())
            end = len(line.rstrip())
            x0 = MARGIN + font.size(text[:start])[0]
            x1 = MARGIN + font.size(text[:end])[0]
            under = text_y + step - 5
            pygame.draw.line(screen, (255, 90, 90), (x0, under), (x1, under), 3)
            source = None
            continue

        if line.startswith("    "):
            color = (255, 170, 170)  # a line of the student's code
        elif line.startswith("  "):
            color = (150, 150, 175)  # a file/line location
        else:
            color = (255, 255, 255)  # the message itself

        pieces = _wrap(line, font, width)
        source = (line, y) if line.startswith("    ") and len(pieces) == 1 else None

        for piece in pieces:
            screen.blit(font.render(piece, True, color), (MARGIN, y))
            y += step
            if y > screen.get_height() - step:
                pygame.display.flip()
                return

    pygame.display.flip()


def _render_plain(screen, lines, note):
    """Fallback used only if the nicer renderer itself fails."""
    font = pygame.font.Font(None, 24)
    screen.fill((12, 12, 20))
    y = MARGIN
    screen.blit(font.render(note, True, (255, 255, 0)), (MARGIN, y))
    y += 26
    for line in lines:
        screen.blit(font.render(line[:80], True, (255, 255, 255)), (MARGIN, y))
        y += 26
        if y > screen.get_height() - 26:
            break
    pygame.display.flip()


def show_error(screen, message, exc=None):
    raw = message.splitlines()
    if exc is not None:
        raw += "".join(
            traceback.format_exception(type(exc), exc, exc.__traceback__)
        ).splitlines()

    print("\n".join(raw))  # also goes to pygbag's terminal

    try:
        _render(screen, _tidy(raw))
    except Exception as inner:
        _render_plain(screen, raw, f"[display fallback: {inner!r}]")


async def freeze():
    """Stop running, but keep the browser tab responsive."""
    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                return
        await asyncio.sleep(0.1)


def start_state(screen):
    """Run setup() and check the result. Returns None if something is wrong."""
    if getattr(game, "setup", None) is None:
        show_error(screen, "game.py needs a setup() function that returns a state.")
        return None

    state = None
    try:
        state = game.setup()
    except Exception as exc:
        show_error(screen, "Error in setup():", exc)
        return None

    if state is None:
        show_error(
            screen,
            "setup() did not return anything.\n"
            "It should end with a line like:  return State()",
        )
        return None

    if getattr(game, "draw", None) is None:
        show_error(screen, "game.py needs a draw(screen, state) function.")
        return None

    return state


def handle(event, state):
    """Send one pygame event to the matching function in game.py."""
    if event.type == pygame.KEYDOWN:
        call("on_key_down", state, event.key)
    elif event.type == pygame.KEYUP:
        call("on_key_up", state, event.key)
    elif event.type == pygame.MOUSEBUTTONDOWN:
        call("on_mouse_down", state, event.pos, event.button)
    elif event.type == pygame.MOUSEBUTTONUP:
        call("on_mouse_up", state, event.pos, event.button)
    elif event.type == pygame.MOUSEMOTION:
        call("on_mouse_move", state, event.pos)


async def main():
    pygame.init()
    screen = pygame.display.set_mode(get_app_size())
    clock = pygame.time.Clock()

    if startup_error is not None:
        show_error(screen, "game.py could not be loaded:", startup_error)
        await freeze()
        return

    state = start_state(screen)
    if state is None:
        await freeze()
        return

    while True:
        try:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    return
                handle(event, state)

            dt = min(clock.tick(FRAMES_PER_SECOND) / 1000, LONGEST_TICK)
            call("on_tick", state, dt)
            call("draw", screen, state)

        except CallbackError as failure:
            show_error(screen, f"Error in {failure.name}():", failure.original)
            await freeze()
            return

        pygame.display.flip()
        await asyncio.sleep(0)


asyncio.run(main())